---
title: "RedDwarfData: a simplified dataset of StarCraft matches"
author: "J. J. Merelo"
date: "27 de noviembre de 2017"
output: pdf_document
abstract: Starcraft is one of the most interesting arenas to test new machine learning and computational intelligence techniques; however, StarCraft matches take a long time and creating a good dataset for training can be hard; besides, analyzing match logs to extract the main characteristics can also be done in many different ways to the point that extracting and processing data itself can take an inordinate amount of time. In this paper we present one such simplified dataset extracted from Robinson and Watson, which we have called RedDwarfData, containing several thousand matches processed to frames, so that temporal studies can also be undertaken. This dataset is available under a free license. An initial analysis and appraisal of these matches is also made. 
bibliography: prediction.bib
---

```{r setup, include=FALSE}
```

# Introduction

\emph{StarCraft} is a well-known Real Time Strategy (\emph{RTS}) game whose first version was released in 1998 [@yoon2001starcraft]. The game consists of two opponents trying to beat each other over a squared arena. Every player has to build workers and buildings using the available resources located over the terrain. There exit three different kinds of species, any of then having different kinds of individuals. Species and individual differ in their skills, so that players have a wide range of possibilities in order to plan their strategies. The need to dynamically take decisions for both the short and the long terms make RTS adequate scenarios to test AI algorithms [@ontanon2013survey] that could be used later in real problems including financial, military and logistics problems. 

\emph{StarCraft} has become popular among researchers thanks to \emph{BWAPI}, an API developed by the community that allows programming artificial agents and that was developed for StarCraft competitions [@buro2012real]. These agents can act just like regular players, according to a previously established algorithm; but, more important, they can collectse data as matches are running. The data collected this way can be later analysed, so that machine learning techniques can be applied for both supervised and unsupervised learning.

Developing and releasing datasets for this task is thus a way of expanding research in this area and allowing researchers to develop their own bots or prediction algorithms without having to scrape them or actually play the games, a time-consuming task, to extract data from them. Several researchers have done so and we will refer to them in the state of the art; in this paper we part from Robertson and Watson's dataset [@RobertsonW14] and create a simpler one that can be used without needing many resources; even so, the data set is balanced with respect to duration, races and number of resources used by the players. 

The rest of the paper is organized as follows: next we will present the Starcraft datasets that have been published so far. In the next section we will show how Robertson and Watson's dataset was processed and the rationale for doing it that way. Then we will present a macro picture of the data set, to eventually draw some conclusions from it and possible lines of work using this dataset.

## State of the art

The main motivation for writing this paper was the proliferation of new StarCraft datasets in the last few years. Players have been uploading their matches command logs to several websites, such as TeamLiquid \footnote{\url{http://www.teamliquid.net}} or BWReplays \footnote{\url{http://www.bwreplays.com}} for over 10 years. These logs are usually employed by the player community to learn new playing techniques from other players. From the point of view of using them for AI training, however, these datasets are in raw form and require some kind of command execution, parsing, data selection and filtering in order to serve as a good base for learning models [@Stardata17]. Moreover, a lot of uploaded replays may be corrupt or incomplete. Different authors have been processing these replays to create datasets that can be used to predict the outcome of a match or a battle or simply gather insights on gaming strategies. The first paper that describes the processing of replays was the one presented by Weber and Mateas [@Weber09], where they processed replays to create a dataset to compare several classification algorithms. 5393 replays were used and they store specific events during the games, not the full game state, validating the possibility of predicting the winner of a game to a certain degree. Later, other datasets that store the full game state to apply generic machine learning techniques have appeared [@Synnaeve12].

Instead providing the game logs directly, Robertson and Watson [@RobertsonW14] distributed the logs in a database, created by obtaining the replays from several replays webpages, executing the game and storing a large number of game features data every certain number of frames. This dataset has been used by other researchers, for example, to create models differentiating by race [@Ravari16].

Recently, and built upon the Synnaeve and Bessiere work [@Synnaeve12], Lin et al. [@Stardata17] have released the largest dataset to date. It includes 65646 replays, storing the full state of the game every 3 frames, including up to 30 features by unit and battle detections, storing all the data in TorchCraft format to be accessed by specific software clients. Even using compression mechanisms, this dataset requires 365GB of space. The aim of using this dataset is to apply Deep Learning algorithms that require a large amount of data.

However, there is not a small and limited dataset ready to use for teaching purposes, for example, to directly use as input for certain algorithms without any modification. This is the reason we have used the Robertson and Watson database [@RobertsonW14] to extract a limited number of features and parsed it directly to CSV (Comma Separated Values) format. These CSV files can be easily downloaded and straightforward parsed with any programming language. %PABLO: Any other ideas to justify our dataset?

## Data extraction and filtering

Six relational databases have been provided by [@RobertsonW14], which means that an intermediate step to produce an usable CSV file is needed. A query which extract data from one single replay has been developed; it is explained on the lines below. A simple function which iterates over all the replays has been developed too, but the most difficult task is parsing individual replays.

Focusing in one single match, identified by it \emph{ReplayID}, the first step is to take the \emph{Duration} and the identifiers \emph{PlayerReplayID} of the two players involved in the game. The \emph{PlayerReplayID} with the minimum value is taken as the first player; this does not actually introduce a bias. 

As a next step, it is important to take a time reference to be able to track the match in every moment. The chosen reference is the \emph{Frame} when a change in resources (\emph{Minerals}, \emph{Gas} and \emph{Supply}) occurs. This instant does not have to be the same for the two players, so all the instants when a change is discovered are saved. This choice implies a lot of empty values in the database; however, this is easily fixed taking the last known value to fill each empty one: if there is not a change for a player, the resources would be the last seen ones.

This decision is also important to track the units: they are valued by their price in resources, and the value recorded in the original database is splitt by regions. To register the value of some units, all the region's values have to be summed up, but the frame when these changes occur are not the same that the  resources' ones, so the last change for each region is saved and accumulated.

These units values are also available in the enemy's direction: the estimation of the enemy's values is recorded in the dataset, so the last proccess is also done for these records.  

With all the data well-formed, only the \emph{ReplayID}, \emph{Winner} and \emph{Duration} have to be added to the match. The data of a game does not have any missing values, so they are ready to be saved. As it was said before, this proccess has to be repeated for each match. 


## The big picture

A few macro analysis of the data in this dataset will allow us to compare it with other datasets and also appraise its balance and general features. The duration of the matches is represented below.

**Include R code for histogram here**

The mode is between 20 and 25 minutes, with average equal to **include variables here** and median **include median**. 

## Conclusions

## References